[package]
name = "trait_only"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[dependencies]
psn_api_rs = { path = "../../", default-features = false }
reqwest = { version = "0.10.0-alpha.1", features = ["json"] }
serde = "1.0.101"
tokio = "=0.2.0-alpha.6"

